{
 "title": "Carbon Footprint",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Carbon footprint - last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nlastCarbonData = from(bucket: \"Carbon\")\n    |> range(start: -24h)\n    |> max(column: \"_time\")\n    |> findColumn(fn: (key) => true, column: \"_time\")\n\npowerConsumption = from(bucket: \"Power\")\n  |> range(start: -24h, stop: lastCarbonData[0])\n  |> filter(fn: (r) => r._measurement == \"consumption\" and r._field == \"value\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"series\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with\n    _value: (r.House + r.Hot_Water)\n  }))\n  |> filter(fn: (r) => r._value > 0)\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time, \n      _value: r._value / 1000.0\n    }))\n  |> window(every: 1h)\n\ncarbonIntensity = from(bucket: \"Carbon\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"carbon\" and r._field == \"value\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> window(every: 1h)\n\njoinedData = join(\n  tables: {power: powerConsumption, carbon: carbonIntensity},\n  on: [\"_start\", \"_stop\"],\n  method: \"inner\"\n)\n|> window(every: 1h, timeColumn: \"_time_carbon\" )\n\ncarbonFootprint = joinedData\n  |> filter(fn: (r) => date.minute(t: r._time_carbon) == 0)\n  |> map(fn: (r) => ({\n      _time: r._time_carbon,\n      carbonFootprint: r._value_power * r._value_carbon\n    })\n  )\n\ncarbonFootprint\n  |> sum(column: \"carbonFootprint\")\n"
    }
   ]
  },
  {
   "title": "Grid Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Carbon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carbon\")\n  |> filter(fn: (r) => r[\"series\"] == \"carbon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Carbon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"renewable\")\n  |> filter(fn: (r) => r[\"series\"] == \"renewable\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Carbon footprint per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "import \"date\"\n\nlastCarbonData = from(bucket: \"Carbon\")\n    |> range(start: -24h)\n    |> max(column: \"_time\")\n    |> findColumn(fn: (key) => true, column: \"_time\")\n\npowerConsumption = from(bucket: \"Power\")\n  |> range(start: -24h, stop: lastCarbonData[0])\n  |> filter(fn: (r) => r._measurement == \"consumption\" and r._field == \"value\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"series\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with\n    _value: (r.House + r.Hot_Water)\n  }))\n  |> filter(fn: (r) => r._value > 0)\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time, \n      _value: r._value / 1000.0\n    }))\n  |> window(every: 1h)\n\ncarbonIntensity = from(bucket: \"Carbon\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"carbon\" and r._field == \"value\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> window(every: 1h)\n\njoinedData = join(\n  tables: {power: powerConsumption, carbon: carbonIntensity},\n  on: [\"_start\", \"_stop\"],\n  method: \"inner\"\n)\n|> window(every: 1h, timeColumn: \"_time_carbon\" )\n\ncarbonFootprint = joinedData\n  |> filter(fn: (r) => date.minute(t: r._time_carbon) == 0)\n  |> map(fn: (r) => ({\n      _time: r._time_carbon,\n      carbonFootprint: r._value_power * r._value_carbon\n    })\n  )\n\ncarbonFootprint\n"
    }
   ]
  },
  {
   "title": "Grid Status - Renewable Energy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Carbon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"renewable\")\n  |> filter(fn: (r) => r[\"series\"] == \"renewable\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> truncateTimeColumn(unit: 1h)"
    }
   ]
  },
  {
   "title": "Total Grid Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Power\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"series\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with\n    _value: (r.House + r.Hot_Water)\n  }))\n  |> filter(fn: (r) => r._value > 0)\n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> yield(name: \"Net Grid\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Status - Carbon Intensity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "from(bucket: \"Carbon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"carbon\")\n  |> filter(fn: (r) => r[\"series\"] == \"carbon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> truncateTimeColumn(unit: 1h)"
    }
   ]
  }
 ]
}