{
 "title": "Power Consumption",
 "time": { "from": "now-28d", "to": "now" },
 "panels": [
  {
   "title": "Generation - Year To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1y)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"Solar\")\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Generation - Month To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1mo)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"Solar\")\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Usage - Year To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1y)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Usage - Month To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1mo)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Draw - Year To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1y)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Draw - Month To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1mo)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Feed-In - Year To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1y)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> filter(fn: (r) => r[\"_value\"] < 0)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Feed-In - Month To Date",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1mo)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> filter(fn: (r) => r[\"_value\"] < 0)\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bill Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\nmonth = date.truncate(t: now(), unit: 1mo)\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 * 0.1413 }))\n  |> yield(name: \"Consumed\")\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"Hot_Water\")\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 * 0.1283 }))\n  |> yield(name: \"Hot Water\")\n\nfrom(bucket: \"Power\")\n  |> range(start: month)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\")\n  |> filter(fn: (r) => r[\"_value\"] < 0)\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 * 0.49 }))\n  |> yield(name: \"Feed-In\")\n\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Usage History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Power\")\n  |> range(start: -28d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"House\" or r[\"series\"] == \"Hot_Water\")\n  |> fill(value: 0.0)\n  |> window(every: 1d)\n  |> sum()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Generation History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Power\")\n  |> range(start: -28d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"consumption\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"series\"] == \"Solar\")\n  |> fill(value: 0.0)\n  |> window(every: 1d)\n  |> sum()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}